config/routes.rb
Rails.application.routes.draw do
  resources :song_infos
  resources :songs
  resources :authors

  root 'authors#index'

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :songs
end

app/models/song.rb
class Song < ActiveRecord::Base
  has_one :song_info
  belongs_to :author
end

app/models/song_info.rb
class SongInfo < ActiveRecord::Base
  belongs_to :song
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name, :country)
    end
end

app/controllers/song_infos_controller.rb
class SongInfosController < ApplicationController
  before_action :set_song_info, only: [:show, :edit, :update, :destroy]

  # GET /song_infos
  # GET /song_infos.json
  def index
    @song_infos = SongInfo.all
  end

  # GET /song_infos/1
  # GET /song_infos/1.json
  def show
  end

  # GET /song_infos/new
  def new
    @song_info = SongInfo.new
  end

  # GET /song_infos/1/edit
  def edit
  end

  # POST /song_infos
  # POST /song_infos.json
  def create
    @song_info = SongInfo.new(song_info_params)

    respond_to do |format|
      if @song_info.save
        format.html { redirect_to @song_info, notice: 'Song info was successfully created.' }
        format.json { render :show, status: :created, location: @song_info }
      else
        format.html { render :new }
        format.json { render json: @song_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /song_infos/1
  # PATCH/PUT /song_infos/1.json
  def update
    respond_to do |format|
      if @song_info.update(song_info_params)
        format.html { redirect_to @song_info, notice: 'Song info was successfully updated.' }
        format.json { render :show, status: :ok, location: @song_info }
      else
        format.html { render :edit }
        format.json { render json: @song_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /song_infos/1
  # DELETE /song_infos/1.json
  def destroy
    @song_info.destroy
    respond_to do |format|
      format.html { redirect_to song_infos_url, notice: 'Song info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song_info
      @song_info = SongInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_info_params
      params.require(:song_info).permit(:duration, :date, :song_id)
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:name, :genre, :author_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/song_infos_helper.rb
module SongInfosHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/authors/_form.html.erb
<%= form_with(model: author, local: true) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
        <% author.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Country</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= author.country %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<p>
  <strong>Country:</strong>
  <%= @author.country %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/song_infos/_form.html.erb
<%= form_with(model: song_info, local: true) do |form| %>
  <% if song_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(song_info.errors.count, "error") %> prohibited this song_info from being saved:</h2>

      <ul>
        <% song_info.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :duration %>
    <%= form.number_field :duration %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.text_field :date %>
  </div>

  <div class="field">
    <%= form.label :song %>
    <%= form.collection_select(:song_id, Song.all, :id, :name) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/song_infos/edit.html.erb
<h1>Editing Song Info</h1>

<%= render 'form', song_info: @song_info %>

<%= link_to 'Show', @song_info %> |
<%= link_to 'Back', song_infos_path %>

app/views/song_infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Song Infos</h1>

<table>
  <thead>
    <tr>
      <th>Duration</th>
      <th>Date</th>
      <th>Song</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @song_infos.each do |song_info| %>
      <tr>
        <td><%= song_info.duration %></td>
        <td><%= song_info.date %></td>
        <td><%= song_info.song.name %></td>
        <td><%= link_to 'Show', song_info %></td>
        <td><%= link_to 'Edit', edit_song_info_path(song_info) %></td>
        <td><%= link_to 'Destroy', song_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Song Info', new_song_info_path %>

app/views/song_infos/new.html.erb
<h1>New Song Info</h1>

<%= render 'form', song_info: @song_info %>

<%= link_to 'Back', song_infos_path %>

app/views/song_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Duration:</strong>
  <%= @song_info.duration %>
</p>

<p>
  <strong>Date:</strong>
  <%= @song_info.date %>
</p>

<p>
  <strong>Song:</strong>
  <%= @song_info.song.name %>
</p>

<%= link_to 'Edit', edit_song_info_path(@song_info) %> |
<%= link_to 'Back', song_infos_path %>

app/views/songs/_form.html.erb
<%= form_with(model: song, local: true) do |form| %>
  <% if song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
        <% song.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :genre %>
    <%= form.text_field :genre %>
  </div>

  <div class="field">
    <%= form.label :author_id %>
    <%= form.collection_select(:author_id, Author.all, :id, :name) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Songs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Genre</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= song.name %></td>
        <td><%= song.genre %></td>
        <td><%= song.author.name %></td>
        <td><%= link_to 'Show', song %></td>
        <td><%= link_to 'Edit', edit_song_path(song) %></td>
        <td><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Song', new_song_path %>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @song.name %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @song.genre %>
</p>

<p>
  <strong>Author:</strong>
  <%= @song.author.name %>
</p>

<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>